### ISSUE TITLE
make search in tweek case insensitive

### ISSUE THREAD

**Issue by mayashoval** [Soluto/tweek-clients#63]
keys with upper case letters aren't returned when searching in tweek editor. example: TipsForShootingBetterVideos_iOS would not return any results.

**Comment by Yshayy** [comment]
Hi @mayashoval, issues for Tweek editor are at the @Soluto/tweek main repository, this repo is for the different client sdks of Tweek.

But in either case, keys in Tweek shouldn't contain uppercase characters (https://docs.tweek.fm/concepts/keys/keys-ands-paths), the editor itself does not allow it when creating new keys. This validation is only applied for new keys created at the editor, keys that were migrated from external systems or added externally don't have these constraints.
We hope to add more validation in other parts of Tweek so these cases would be avoided.

However - search in Tweek is scanning other parameters as well, such as description, tags, name, etc...
The other fields can definitely have mixed casing and we should support it. (it would probably solve your problem as well since it's the same mechanism).
I'll open up an issue in Tweek's main repo
